#!/system/bin/sh

set_perm() {
    chown $1.$2 $4
    chown $1:$2 $4
    chmod $3 $4
}

ch_con() {
    chcon u:object_r:system_file:s0 $1
}

ch_con_ext() {
    chcon $2 $1
}

echo "**************************"
echo "  superSU installer -sdc  "
echo "**************************"

echo "- Mounting /system, /data and rootfs"
mount -o rw,remount /dev/block/mmcblk0p9 /data
mount -o rw,remount /dev/block/mmcblk0p8 /system
mount -o rw,remount /


ABI=$(cat /system/build.prop | grep ro.product.cpu.abi= | dd bs=1 skip=19 count=3)
ABI2=$(cat /system/build.prop | grep ro.product.cpu.abi2= | dd bs=1 skip=20 count=3)

ARCH=arm
if [ "$ABI" = "x86" ] || [ "$ABI2" = "x86" ]; then
    ARCH=x86
fi

API=$(cat /system/build.prop | grep ro.build.version.sdk= | dd bs=1 skip=21 count=2)

SUMOD=06755
SUGOTE=false
MKSH=/system/bin/mksh
if [ "$API" -eq "$API" ] && [ "$API" -gt "17" ]; then
      SUMOD=0755
      SUGOTE=true
fi
if [ ! -f $MKSH ]; then
  MKSH=/system/bin/sh
fi

BIN=$ARCH
COM=common

echo "- Disabling OTA survival"
chmod 0755 $BIN/chattr
chmod 0755 $BIN/chattr.pie

if [ -f /system/xbin/su ]; then
    $BIN/chattr -i /system/xbin/su
    $BIN/chattr.pie -i /system/xbin/su
fi

if [ -f /system/bin/.ext/.su ]; then
    $BIN/chattr -i /system/bin/.ext/.su
    $BIN/chattr.pie -i /system/bin/.ext/.su
fi

if [ -f /system/xbin/daemonsu ]; then
    $BIN/chattr -i /system/xbin/daemonsu
    $BIN/chattr.pie -i /system/xbin/daemonsu
fi

if [ -f /system/etc/install-recovery.sh ]; then
    $BIN/chattr -i /system/etc/install-recovery.sh
    $BIN/chattr.pie -i /system/etc/install-recovery.sh
fi

if [ -f /system/etc/install-recovery.sh ]; then
    # check the contents of install-recovery.sh
    export CHECK1="/system/xbin/daemonsu"
    export CHECK2="/system/etc/install-recovery-2.sh"

    if grep -qs $CHECK1 /system/etc/install-recovery.sh || grep -qs $CHECK2 /system/etc/install-recovery.sh; then
        # check if install-recovery.sh loads deamonsu
        if grep -qs $CHECK1 /system/etc/install-recovery.sh; then
            echo "install-recovery.sh contains this line: $CHECK1 this can cause boot loops so:"
            echo "install-recovery.sh will not be copied to install-recovery-2.sh"
            echo ""
        fi
        # check if install-recovery.sh launches install-recovery-2.sh
        if grep -qs $CHECK2 /system/etc/install-recovery.sh; then
            echo "install-recovery.sh contains this line: $CHECK2 this can cause boot loops so:"
            echo "install-recovery.sh will not be copied to install-recovery-2.sh"
            echo ""
        fi
    elif [ ! -f /system/etc/install-recovery-2.sh ]; then
        echo "copy install-recovery.sh to install-recovery-2.sh "
        cp /system/etc/install-recovery.sh /system/etc/install-recovery-2.sh
        echo ""
    else
        echo "/system/etc/install-recovery-2.sh already exist"
        echo ""
    fi
fi

echo "- Removing old files"
rm -f /system/bin/su
rm -f /system/xbin/su
rm -f /system/xbin/sudo
rm -f /system/xbin/super
rm -f /system/xbin/.tmpsu
rm -f /system/xbin/daemonsu
rm -f /system/xbin/sugote
rm -f /system/xbin/sugote-mksh
rm -f /system/bin/.ext/.su
rm -f /system/etc/install-recovery.sh
rm -f /system/etc/init.d/99SuperSUDaemon
rm -f /system/etc/.installed_su_daemon
rm -f /system/app/Superuser.apk
rm -f /system/app/Superuser.odex
rm -f /system/app/SuperUser.apk
rm -f /system/app/SuperUser.odex
rm -f /system/app/superuser.apk
rm -f /system/app/superuser.odex
rm -f /system/app/Supersu.apk
rm -f /system/app/Supersu.odex
rm -f /system/app/SuperSU.apk
rm -f /system/app/SuperSU.odex
rm -f /system/app/supersu.apk
rm -f /system/app/supersu.odex

rm -f /data/dalvik-cache/*com.noshufou.android.su*
rm -f /data/dalvik-cache/*com.koushikdutta.superuser*
rm -f /data/dalvik-cache/*com.mgyun.shua.su*
rm -f /data/dalvik-cache/*Superuser.apk*
rm -f /data/dalvik-cache/*SuperUser.apk*
rm -f /data/dalvik-cache/*superuser.apk*
rm -f /data/dalvik-cache/*eu.chainfire.supersu*
rm -f /data/dalvik-cache/*Supersu.apk*
rm -f /data/dalvik-cache/*SuperSU.apk*
rm -f /data/dalvik-cache/*supersu.apk*
rm -f /data/dalvik-cache/*.oat
rm -f /data/app/com.noshufou.android.su-*
rm -f /data/app/com.koushikdutta.superuser-*
rm -f /data/app/com.mgyun.shua.su-*
rm -f /data/app/eu.chainfire.supersu-*

echo "- Placing files"

FOLDER=/system/bin/.ext
if [ ! -d "$FOLDER" ]; then
    mkdir -p "$FOLDER"
fi

cp $BIN/su /system/xbin/daemonsu
cp $BIN/su /system/xbin/su

if ($SUGOTE); then
    cp $BIN/su /system/xbin/sugote
    cp $MKSH /system/xbin/sugote-mksh
fi

cp $BIN/su /system/bin/.ext/.su
cp $COM/Superuser.apk /system/app/Superuser.apk
cp $COM/install-recovery.sh /system/etc/install-recovery.sh
echo 1 > /system/etc/.installed_su_daemon

echo "- Setting permissions"
set_perm 0 0 0777 /system/bin/.ext
set_perm 0 0 $SUMOD /system/bin/.ext/.su
set_perm 0 0 $SUMOD /system/xbin/su

if ($SUGOTE); then
  set_perm 0 0 0755 /system/xbin/sugote
  set_perm 0 0 0755 /system/xbin/sugote-mksh
fi

set_perm 0 0 0755 /system/xbin/daemonsu
set_perm 0 0 0755 /system/etc/install-recovery.sh
set_perm 0 0 0755 /system/etc/install-recovery-2.sh
set_perm 0 0 0644 /system/etc/.installed_su_daemon
set_perm 0 0 0644 /system/app/Superuser.apk

#ch_con /system/bin/.ext/.su
#ch_con /system/xbin/su

#if ($SUGOTE); then
#    ch_con_ext /system/xbin/sugote u:object_r:zygote_exec:s0
#    ch_con /system/xbin/sugote-mksh
#fi

#ch_con /system/xbin/daemonsu
#ch_con /system/etc/install-recovery.sh
#ch_con /system/etc/.installed_su_daemon
#ch_con /system/app/Superuser.apk

echo "- Post-installation script"
/system/xbin/su --install

echo "- remounting /system as read only"
mount -o ro,remount /system

echo "- Cleaning up"
rm /tmp/$BIN/*
rm /tmp/$COM/*
rmdir /tmp/$BIN
rmdir /tmp/$COM

echo "- Done ! superSU installation complete"
exit 0
